name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            if [ ! -d "/home/gyumin/port_shop/.git" ]; then
              echo "Git 저장소가 아닙니다. 기존 폴더를 삭제하고 새로 clone 합니다."
              rm -rf /home/gyumin/port_shop
              cd /home/gyumin
              git clone https://github.com/gyuminiai82/port_shop.git
              cd port_shop
            else
              echo "프로젝트 폴더가 존재합니다. 최신 코드를 당겨옵니다."
              cd /home/gyumin/port_shop
              git fetch --all
              git reset --hard origin/main
            fi
            
            # 런타임 및 빌드 시 필요한 .env 파일을 서버에 동적으로 자동 생성합니다.
            echo 'REDIS_URL="redis://:03040228@192.168.0.2:6379/0"' > .env
            echo 'DATABASE_URL="postgresql://gyumin:03040228@192.168.0.2:5432/PORT_SHOP?schema=public"' >> .env
            echo 'NEXT_PUBLIC_SITE_URL="https://shop.minstudio.app"' >> .env
            
            # 도커 이미지를 새로 빌드하고 재시작합니다.
            docker compose up -d --build
